# This is a basic workflow to help you get started with Actions
- name: Create S3
  uses: aitorres/aws-s3-create-bucket
  with:
    bucket-name: 'fita_DevOpst'
    aws-access-key-id: 'AKIA53LXRVYJ6HG5GUW5'
    aws-secret-access-key: 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACAh1nMGDXNBkwwWjGIlYM2z4OBvAmOduHccdjnaJ8fpDAAAAIjuSAjC7kgIwgAAAAtzc2gtZWQyNTUxOQAAACAh1nMGDXNBkwwWjGIlYM2z4OBvAmOduHccdjnaJ8fpDAAAAEAwUQIBATAFBgMrZXAEIgQgS5sHf9b84YHRCkL6Ht3xvyHWcwYNc0GTDBaMYiVgzbPg4G8CY524dxx2Odonx+kMAAAAAAECAwQF'
    aws-region: 'us-west-1'
    acl: 'private'
