# This is a basic workflow to help you get started with Actions

  uses: vinetaru/aws-s3-create-bucket@v1.2.0
  with:
    bucket-name: 'fita_DevOps'
    #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-access-key-id: 'AKIA53LXRVYJ6HG5GUW5'
    aws-secret-access-key: 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACAh1nMGDXNBkwwWjGIlYM2z4OBvAmOduHccdjnaJ8fpDAAAAIjuSAjC7kgIwgAAAAtzc2gtZWQyNTUxOQAAACAh1nMGDXNBkwwWjGIlYM2z4OBvAmOduHccdjnaJ8fpDAAAAEAwUQIBATAFBgMrZXAEIgQgS5sHf9b84YHRCkL6Ht3xvyHWcwYNc0GTDBaMYiVgzbPg4G8CY524dxx2Odonx+kMAAAAAAECAwQF'
    aws-region: 'us-west-1'
    acl: 'private'
